// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: proto/tx.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sol_SendBlockTxs_FullMethodName = "/proto.Sol/SendBlockTxs"
)

// SolClient is the client API for Sol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolClient interface {
	SendBlockTxs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendBlockTxsReq, emptypb.Empty], error)
}

type solClient struct {
	cc grpc.ClientConnInterface
}

func NewSolClient(cc grpc.ClientConnInterface) SolClient {
	return &solClient{cc}
}

func (c *solClient) SendBlockTxs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendBlockTxsReq, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sol_ServiceDesc.Streams[0], Sol_SendBlockTxs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendBlockTxsReq, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sol_SendBlockTxsClient = grpc.ClientStreamingClient[SendBlockTxsReq, emptypb.Empty]

// SolServer is the server API for Sol service.
// All implementations must embed UnimplementedSolServer
// for forward compatibility.
type SolServer interface {
	SendBlockTxs(grpc.ClientStreamingServer[SendBlockTxsReq, emptypb.Empty]) error
	mustEmbedUnimplementedSolServer()
}

// UnimplementedSolServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolServer struct{}

func (UnimplementedSolServer) SendBlockTxs(grpc.ClientStreamingServer[SendBlockTxsReq, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method SendBlockTxs not implemented")
}
func (UnimplementedSolServer) mustEmbedUnimplementedSolServer() {}
func (UnimplementedSolServer) testEmbeddedByValue()             {}

// UnsafeSolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolServer will
// result in compilation errors.
type UnsafeSolServer interface {
	mustEmbedUnimplementedSolServer()
}

func RegisterSolServer(s grpc.ServiceRegistrar, srv SolServer) {
	// If the following call pancis, it indicates UnimplementedSolServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sol_ServiceDesc, srv)
}

func _Sol_SendBlockTxs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SolServer).SendBlockTxs(&grpc.GenericServerStream[SendBlockTxsReq, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sol_SendBlockTxsServer = grpc.ClientStreamingServer[SendBlockTxsReq, emptypb.Empty]

// Sol_ServiceDesc is the grpc.ServiceDesc for Sol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sol",
	HandlerType: (*SolServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendBlockTxs",
			Handler:       _Sol_SendBlockTxs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/tx.proto",
}
